# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  web:
    build: .
    container_name: sitioweb
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./apps:/usr/share/nginx/html
    depends_on:
      - db
